# Generated by Django 4.0.4 on 2022-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
